name: Build, test and deploy

env:
  APTOS_VERSION: "1.0.7"
  NODE_URL: https://fullnode.testnet.aptoslabs.com/v1

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: aptos-cli-v${{ env.APTOS_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create concordia account
        run: cd ${{ env.HOME }} && aptos init --profile concordia --network custom --rest-url ${{ env.NODE_URL }} --skip-faucet

      - name: Fund concordia account
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 8
          command: cd ${{ env.HOME }} && aptos account transfer --amount 2000000 --account concordia --private-key 0x${{ secrets.APTOS_FUNDING_KEY }} --url ${{ env.NODE_URL }} --assume-yes

      - name: Build wallet lib
        run: |
          yarn
          yarn format
          yarn build
          git diff --exit-code
        working-directory: lib/wallet

      - name: Build moneygun lib
        run: |
          yarn
          yarn format
          yarn build
          git diff --exit-code
        working-directory: lib/moneygun

      - name: Build concordacle lib
        run: |
          yarn
          yarn format
          yarn build
          git diff --exit-code
        working-directory: lib/concordacle

      - run: yarn
        working-directory: examples

      - run: yarn ping
        working-directory: examples

      - run: yarn init-profile
        working-directory: examples

      - run: yarn lend
        working-directory: examples

      - run: yarn update-prices
        working-directory: examples

      - run: yarn borrow
        working-directory: examples
