name: Build and deploy

env:
  APTOS_VERSION: "1.0.7"
  NODE_URL: https://fullnode.testnet.aptoslabs.com/v1

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  create-and-fund-accounts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: aptos-cli-v${{ env.APTOS_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create concordia account
        run: aptos init --profile concordia --network custom --rest-url ${{ env.NODE_URL }} --skip-faucet

      - name: Fund concordia account
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 8
          command: aptos account transfer --amount 1000000 --account concordia --private-key 0x${{ secrets.APTOS_FUNDING_KEY }} --url ${{ env.NODE_URL }} --assume-yes

      - uses: actions/upload-artifact@v3
        with:
          name: aptos-config
          path: .aptos/config.yaml
          retention-days: 1

  test-sdk:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [
      create-and-fund-accounts
    ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: aptos-config
          path: ~/.aptos

      - run: yarn
        working-directory: examples

      - run: yarn ping
        working-directory: examples

      - run: yarn init-profile
        working-directory: examples

      - run: yarn lend
        working-directory: examples
